import java.util.Arrays;
import java.util.EnumMap;
import java.util.HashMap;

enum Move {
  ROCK("rock"),
  PAPER("paper"),
  SCISSORS("scissors");

  private final String value;

  Move(String value) {
    this.value = value;
  }
}

public class Challenge2 {
  private final HashMap<String, Integer> points = new HashMap<>();
  private final EnumMap<Move, Integer> movePoints = new EnumMap<>(Move.class);
  private final HashMap<String, Move> move = new HashMap<>();
  private final HashMap<String, String> outcome = new HashMap<>();

  public static void main(String[] args) {
    var c2 = new Challenge2();
    var result1 = c2.calculatePointsWithGivenMoves();
    var result2 = c2.calculatePointWithGivenOutcome();

    System.out.println(result1);
    System.out.println(result2);
  }

  public Integer calculatePointWithGivenOutcome() {
    var input = getInput();
    setMoves();
    setPoints();
    setOutcome();
    setMovePoints();

    return Arrays.stream(input)
        .map(x -> x.split(" "))
        .map(x -> getOutcomePoints(x[0], x[1]))
        .mapToInt(x -> x)
        .sum();
  }

  public Integer calculatePointsWithGivenMoves() {
    var input = getInput();
    setMoves();
    setPoints();

    return Arrays.stream(input)
        .map(x -> x.split(" "))
        .map(x -> getPointsWithGivenMoves(x[0], x[1]))
        .mapToInt(x -> x)
        .sum();
  }

  private Integer getPointsWithGivenOutcome(Move self, String outcome) {
    var movePoint = movePoints.get(self);
    var resultPoints = points.get(outcome);

    return movePoint + resultPoints;
  }

  private Integer getPointsWithGivenMoves(String opponent, String self) {
    var result = getOutcome(opponent, self);

    var movePoints = points.get(self);
    var resultPoints = points.get(result);

    return movePoints + resultPoints;
  }

  private void setPoints() {
    points.put("X", 1);
    points.put("Y", 2);
    points.put("Z", 3);
    points.put("W", 6);
    points.put("D", 3);
    points.put("L", 0);
  }

  private void setMovePoints() {
    movePoints.put(Move.ROCK, 1);
    movePoints.put(Move.PAPER, 2);
    movePoints.put(Move.SCISSORS, 3);
  }

  private void setMoves() {
    move.put("A", Move.ROCK);
    move.put("X", Move.ROCK);
    move.put("B", Move.PAPER);
    move.put("Y", Move.PAPER);
    move.put("C", Move.SCISSORS);
    move.put("Z", Move.SCISSORS);
  }

  private void setOutcome() {
    outcome.put("X", "L");
    outcome.put("Y", "D");
    outcome.put("Z", "W");
  }

  private Integer getOutcomePoints(String opponent, String o) {
    Move opponentMove = move.get(opponent);
    String matchResult = outcome.get(o);

    var counterMove = getCounter(matchResult, opponentMove);

    return getPointsWithGivenOutcome(counterMove, matchResult);
  }

  private Move getCounter(String outcome, Move opponent) {
    if (outcome.equals("W")) {
      return getWinMove(opponent);
    }

    if (outcome.equals("L")) {
      return getLoseMove(opponent);
    }

    return opponent;
  }

  private Move getWinMove(Move opponent) {
    if (opponent.equals(Move.ROCK)) {
      return Move.PAPER;
    }

    if (opponent.equals(Move.PAPER)) {
      return Move.SCISSORS;
    }

    return Move.ROCK;
  }

  private Move getLoseMove(Move opponent) {
    if (opponent.equals(Move.ROCK)) {
      return Move.SCISSORS;
    }

    if (opponent.equals(Move.PAPER)) {
      return Move.ROCK;
    }

    return Move.PAPER;
  }

  private String getOutcome(String opponent, String self) {
    var opponentMove = move.get(opponent);
    var selfMove = move.get(self);

    if (opponentMove.equals(selfMove)) {
      return "D";
    }

    if (opponentMove.equals(Move.ROCK) && selfMove.equals(Move.SCISSORS)) {
      return "L";
    }

    if (opponentMove.equals(Move.PAPER) && selfMove.equals(Move.ROCK)) {
      return "L";
    }

    if (opponentMove.equals(Move.SCISSORS) && selfMove.equals(Move.PAPER)) {
      return "L";
    }

    return "W";
  }

  private String[] getInput() {
    var input = "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "B Y\n" +
        "A Z\n" +
        "C X\n" +
        "B X\n" +
        "C X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B Y\n" +
        "B X\n" +
        "B Y\n" +
        "C Z\n" +
        "C Y\n" +
        "C Z\n" +
        "A X\n" +
        "C Z\n" +
        "B X\n" +
        "C Z\n" +
        "B Y\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "A Y\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "B Y\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Y\n" +
        "C Y\n" +
        "A X\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "C Z\n" +
        "C Z\n" +
        "A X\n" +
        "B X\n" +
        "C Z\n" +
        "A Z\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "C Y\n" +
        "A X\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Z\n" +
        "B Z\n" +
        "A X\n" +
        "A X\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "A Z\n" +
        "C X\n" +
        "A Z\n" +
        "B Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "A X\n" +
        "B Y\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "A Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "A Z\n" +
        "C Y\n" +
        "C Y\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "A Z\n" +
        "B Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B Y\n" +
        "A X\n" +
        "C Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "A Z\n" +
        "B X\n" +
        "A Y\n" +
        "C Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A Z\n" +
        "A Y\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "B Z\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "C Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "C Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Y\n" +
        "C X\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "C X\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "A Z\n" +
        "C X\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "A X\n" +
        "B X\n" +
        "C X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "C Y\n" +
        "C Z\n" +
        "A X\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "C Y\n" +
        "A X\n" +
        "A Y\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "C X\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "C Z\n" +
        "A X\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "A X\n" +
        "C Z\n" +
        "A Z\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "A X\n" +
        "B X\n" +
        "B Y\n" +
        "C Z\n" +
        "B Y\n" +
        "B Z\n" +
        "C Y\n" +
        "C Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "B X\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "A Y\n" +
        "C Z\n" +
        "C X\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "C X\n" +
        "B Z\n" +
        "A X\n" +
        "A Y\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "C Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "C Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "C Z\n" +
        "B Y\n" +
        "C Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Y\n" +
        "C Z\n" +
        "A Z\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "A X\n" +
        "B Y\n" +
        "A X\n" +
        "B Y\n" +
        "A Y\n" +
        "C X\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "B Y\n" +
        "B Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "C Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "C Y\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "A X\n" +
        "A Y\n" +
        "C X\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "A Y\n" +
        "B Y\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "A Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "B X\n" +
        "A X\n" +
        "B Y\n" +
        "B Z\n" +
        "B Y\n" +
        "A Z\n" +
        "C Y\n" +
        "B Z\n" +
        "A X\n" +
        "A Z\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "A X\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "C X\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "A Z\n" +
        "B X\n" +
        "B Y\n" +
        "A Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "C X\n" +
        "B Z\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B Y\n" +
        "C Y\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "C X\n" +
        "A Y\n" +
        "A Y\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Y\n" +
        "C Z\n" +
        "C Y\n" +
        "A Y\n" +
        "A Y\n" +
        "C X\n" +
        "C Z\n" +
        "C Y\n" +
        "C Y\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "C Y\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "A X\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "C X\n" +
        "A X\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "A X\n" +
        "C X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "C Y\n" +
        "B Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A Y\n" +
        "A Z\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Y\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B Y\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "A X\n" +
        "A Z\n" +
        "C X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B Y\n" +
        "C Z\n" +
        "C Y\n" +
        "A X\n" +
        "A Y\n" +
        "A X\n" +
        "A Y\n" +
        "C Z\n" +
        "C Y\n" +
        "C Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A X\n" +
        "C Z\n" +
        "B X\n" +
        "C X\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "A X\n" +
        "A Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "C Y\n" +
        "C Y\n" +
        "C X\n" +
        "B Z\n" +
        "B X\n" +
        "B Y\n" +
        "A X\n" +
        "B Z\n" +
        "B Y\n" +
        "C Y\n" +
        "C Y\n" +
        "C Z\n" +
        "A Z\n" +
        "A X\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "C Z\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "C Z\n" +
        "C Y\n" +
        "A X\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "A Z\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "C Z\n" +
        "C Y\n" +
        "A X\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "A Y\n" +
        "C X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C X\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "A Z\n" +
        "A Y\n" +
        "A Z\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "A X\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "A X\n" +
        "B X\n" +
        "B Y\n" +
        "C X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "C Y\n" +
        "C Z\n" +
        "A Z\n" +
        "C Z\n" +
        "A X\n" +
        "C Z\n" +
        "B Y\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "A Y\n" +
        "A Z\n" +
        "A X\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "A Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C X\n" +
        "A X\n" +
        "A X\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "A X\n" +
        "A Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "A X\n" +
        "A X\n" +
        "B Z\n" +
        "A Z\n" +
        "B Y\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Y\n" +
        "A X\n" +
        "A Z\n" +
        "B Z\n" +
        "A Z\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "A Z\n" +
        "B Y\n" +
        "A Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C X\n" +
        "A X\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Y\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "A Z\n" +
        "A Z\n" +
        "B Y\n" +
        "B Y\n" +
        "C Z\n" +
        "C Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "C X\n" +
        "C Y\n" +
        "C X\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "C X\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "C Z\n" +
        "C Z\n" +
        "C Z\n" +
        "A Y\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "A X\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "A X\n" +
        "A X\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B Y\n" +
        "A Y\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "C X\n" +
        "C Z\n" +
        "B Z\n" +
        "C Z\n" +
        "A X\n" +
        "B Z\n" +
        "C X\n" +
        "B Z\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "A Y\n" +
        "A Y\n" +
        "C Y\n" +
        "C Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "A Z\n" +
        "C Y\n" +
        "C Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "A X\n" +
        "C Z\n" +
        "C Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "C Z\n" +
        "B X\n" +
        "C Z\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "A X\n" +
        "A Y\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "A X\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "C X\n" +
        "C Y\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "A Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "A Y\n" +
        "C Y\n" +
        "B Y\n" +
        "A X\n" +
        "B Y\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A Z\n" +
        "B Z\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "C X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "C X\n" +
        "B Y\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "A X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "C X\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "C Y\n" +
        "B Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A Z\n" +
        "B Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A Z\n" +
        "C X\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "A Z\n" +
        "A Y\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "A X\n" +
        "A Y\n" +
        "A Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "C Z\n" +
        "A X\n" +
        "C Z\n" +
        "C Y\n" +
        "C Y\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "A Z\n" +
        "B Z\n" +
        "A Z\n" +
        "A Y\n" +
        "C Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "A X\n" +
        "A Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C X\n" +
        "A Y\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "C X\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "A Y\n" +
        "C Y\n" +
        "B Z\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "C Y\n" +
        "A Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "A Z\n" +
        "A X\n" +
        "A Y\n" +
        "A Y\n" +
        "A Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "B Z\n" +
        "B Y\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "C Z\n" +
        "C Z\n" +
        "C Y\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "A Z\n" +
        "C Z\n" +
        "A Y\n" +
        "C Z\n" +
        "C Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "A Z\n" +
        "B Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Y\n" +
        "B Z\n" +
        "A Z\n" +
        "A X\n" +
        "B X\n" +
        "C Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "C Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B Y\n" +
        "B Z\n" +
        "C X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Y\n" +
        "B Z\n" +
        "A X\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "A Z\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "C Z\n" +
        "A Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "B Y\n" +
        "C Z\n" +
        "B X\n" +
        "A Y\n" +
        "C X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B Z\n" +
        "B Z\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "C X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "A Z\n" +
        "C Z\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "C Z\n" +
        "B X\n" +
        "A Z\n" +
        "C Y\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "A X\n" +
        "C Y\n" +
        "C Z\n" +
        "A X\n" +
        "A Z\n" +
        "B X\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Z\n" +
        "C Z\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "A Z\n" +
        "A X\n" +
        "C X\n" +
        "B Z\n" +
        "B Y\n" +
        "C Z\n" +
        "C Z\n" +
        "A Y\n" +
        "A Y\n" +
        "A Y\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Y\n" +
        "A Y\n" +
        "C Z\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "B X\n" +
        "C Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B X\n" +
        "C X\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "A Y\n" +
        "C Y\n" +
        "C Y\n" +
        "C Z\n" +
        "A Y\n" +
        "C Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "C Y\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "C Y\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "B Y\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "A Z\n" +
        "C Y\n" +
        "A Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "C Y\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "C Z\n" +
        "A Y\n" +
        "C X\n" +
        "B Z\n" +
        "A Y\n" +
        "A Y\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "C X\n" +
        "A Y\n" +
        "A X\n" +
        "C Y\n" +
        "A Z\n" +
        "A X\n" +
        "C Y\n" +
        "A Y\n" +
        "C Y\n" +
        "A Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "A Y\n" +
        "B Z\n" +
        "A Z\n" +
        "A Y\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "C Y\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "A Z\n" +
        "A X\n" +
        "B X\n" +
        "A Z\n" +
        "B Z\n" +
        "A Z\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "A X\n" +
        "A X\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "A Y\n" +
        "A X\n" +
        "C Z\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "A Y\n" +
        "C Z\n" +
        "C Y\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "A Z\n" +
        "B Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A Z\n" +
        "B X\n" +
        "A Y\n" +
        "A Y\n" +
        "C Y\n" +
        "A Z\n" +
        "B X\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "B Y\n" +
        "B X\n" +
        "A Y\n" +
        "A X\n" +
        "C Z\n" +
        "B Y\n" +
        "C Y\n" +
        "B X\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "A Z\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "A X\n" +
        "B Z\n" +
        "A Y\n" +
        "B Z\n" +
        "A X\n" +
        "C X\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "A X\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "C Y\n" +
        "A X\n" +
        "A X\n" +
        "B X\n" +
        "B Y\n" +
        "B Z\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "A Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "C X\n" +
        "C Z\n" +
        "B X\n" +
        "B Y\n" +
        "A Z\n" +
        "C Z\n" +
        "A X\n" +
        "C Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "A X\n" +
        "C Z\n" +
        "B Z\n" +
        "A Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "B X\n" +
        "C Y\n" +
        "B Y\n" +
        "A X\n" +
        "A X\n" +
        "B Y\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "A X\n" +
        "C Z\n" +
        "C Z\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Y\n" +
        "C Y\n" +
        "B Y\n" +
        "B Y\n" +
        "A Y\n" +
        "B Z\n" +
        "C Y\n" +
        "A X\n" +
        "C Z\n" +
        "B X\n" +
        "B Z\n" +
        "C Y\n" +
        "A Y\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "A Z\n" +
        "A Z\n" +
        "A Z\n" +
        "A Y\n" +
        "C Z\n" +
        "A Z\n" +
        "B X\n" +
        "C Z\n" +
        "B Z\n" +
        "B X\n" +
        "C X\n" +
        "A Z\n" +
        "B Y\n" +
        "A Y\n" +
        "B Y\n" +
        "C Y\n" +
        "B X\n" +
        "A X\n" +
        "A X\n" +
        "A Y\n" +
        "A Y\n" +
        "A X\n" +
        "B Y\n" +
        "B Z\n" +
        "B X\n" +
        "A X\n" +
        "C Y\n" +
        "B X\n" +
        "B Y\n" +
        "A Y\n" +
        "C Y\n" +
        "A Y\n" +
        "B Z\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "B Z\n" +
        "C Z\n" +
        "C Y\n" +
        "A Z\n" +
        "B X\n" +
        "B X\n" +
        "A Y\n" +
        "C Y\n" +
        "B X\n" +
        "B Z\n" +
        "B X\n" +
        "C Z\n" +
        "A Z\n" +
        "B X\n" +
        "C Z\n" +
        "B X\n" +
        "B X\n" +
        "B X\n" +
        "B Z\n" +
        "C Z\n" +
        "C Z\n" +
        "B X\n" +
        "C Y\n" +
        "B Z\n" +
        "C Z\n" +
        "B Z\n" +
        "C Z\n" +
        "B Y\n" +
        "B X\n" +
        "C Z\n" +
        "A X\n" +
        "B X\n" +
        "B X\n" +
        "C Y\n" +
        "B Z";

    return input.split("\n");
  }
}
